gripper_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - finger_width
    state_interfaces:
      - position
      - velocity
    command_interfaces:
      - position
    gains:
      finger_width:
        p: 500.0
        d: 10.0
        i: 0.0
        i_clamp: 1.0
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 2.0
      finger_width: { goal: 0.001, trajectory: 0.001 }

gripper_2fg7:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - finger_width
    state_interfaces:
      - position
      - velocity
    command_interfaces:
      - position

gripper_rg2:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - finger_width
    state_interfaces:
      - position
      - velocity
    command_interfaces:
      - position

gripper_3fg15:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - finger_width
    state_interfaces:
      - position
      - velocity
    command_interfaces:
      - position