move_group:
  ros__parameters:
    kinematics:
      ur_onrobot_manipulator:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_timeout: 0.05
        kinematics_solver_attempts: 3
        position_only_ik: false
        optimize_iterations: 200
        solve_type: Speed

      manipulator:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.005
        kinematics_solver_timeout: 0.1
        kinematics_solver_attempts: 5
        position_only_ik: false
        optimize_iterations: 200
        solve_type: Speed

      ur_onrobot_gripper:
        kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        kinematics_solver_search_resolution: 0.001
        kinematics_solver_timeout: 0.05
        kinematics_solver_attempts: 3