/**:
  ros__parameters:
    moveit_simple_controller_manager:
      ros__parameters:
        controller_names:
          - scaled_joint_trajectory_controller
          - finger_width_trajectory_controller

        scaled_joint_trajectory_controller:
          type: follow_joint_trajectory/FollowJointTrajectory
          action_ns: follow_joint_trajectory
          default: true
          joints:
            - shoulder_pan_joint
            - shoulder_lift_joint
            - elbow_joint
            - wrist_1_joint
            - wrist_2_joint
            - wrist_3_joint
          constraints:
            goal_time: 0.6
            stopped_velocity_tolerance: 0.05

        finger_width_trajectory_controller:
          type: follow_joint_trajectory/FollowJointTrajectory
          action_ns: follow_joint_trajectory
          default: false
          joints:
            - finger_width
          constraints:
            goal_time: 1.0
            stopped_velocity_tolerance: 0.01