controller_manager_ns: controller_manager
controller_list:
  - name: scaled_joint_trajectory_controller
    type: follow_joint_trajectory/FollowJointTrajectory
    default: true
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.01
      shoulder_pan_joint: {trajectory: 0.05, goal: 0.05}
      shoulder_lift_joint: {trajectory: 0.05, goal: 0.05}
      elbow_joint: {trajectory: 0.05, goal: 0.05}
      wrist_1_joint: {trajectory: 0.05, goal: 0.05}
      wrist_2_joint: {trajectory: 0.05, goal: 0.05}
      wrist_3_joint: {trajectory: 0.05, goal: 0.05}
  - name: joint_trajectory_controller
    type: follow_joint_trajectory/FollowJointTrajectory
    default: false
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.01
  - name: finger_width_trajectory_controller
    type: follow_joint_trajectory/FollowJointTrajectory
    default: false
    joints:
      - finger_width
    constraints:
      goal_time: 1.0
      stopped_velocity_tolerance: 0.01
      finger_width: {trajectory: 0.005, goal: 0.005}