ros__parameters:
  planning_pipelines_pipeline_configs:
    ompl:
      pipeline_id: ompl
      planning_plugins:
        - "ompl_interface/OMPLPlanner"
      request_adapters:
        - "default_planner_request_adapters/AddTimeOptimalParameterization"
        - "default_planner_request_adapters/FixWorkspaceBounds"
        - "default_planner_request_adapters/FixStartStateBounds"
        - "default_planner_request_adapters/FixStartStateCollision"
        - "default_planner_request_adapters/FixStartStatePathConstraints"
      response_adapters:
        - "default_planning_response_adapters/AddTimeOptimalParameterization"
        - "default_planning_response_adapters/ValidateSolution"
      start_state_max_bounds_error: 0.1