controller_manager:
  ros__parameters:
    # Posiciones iniciales del brazo UR
    initial_shoulder_pan_joint:   1.57
    initial_shoulder_lift_joint: -1.57
    initial_elbow_joint:          1.57
    initial_wrist_1_joint:       -1.57
    initial_wrist_2_joint:       -1.57
    initial_wrist_3_joint:        0.0

    # Posici√≥n inicial del gripper OnRobot
    initial_finger_joint:         0.060